FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app

COPY pyproject.toml ./
COPY requirements-dev.txt ./

RUN python -m pip install --upgrade pip \
    && python -m pip install -r requirements-dev.txt

COPY . .

RUN useradd --create-home --shell /bin/bash prometheus \
    && chown -R prometheus:prometheus /app

USER prometheus

CMD ["python", "--version"]
